import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import { OpenAI } from "openai"
import { useState } from "react"
import { StoredValue } from "../common/types"
import { Header } from "components/Header"
import { StoryReader } from "components/StoryReader"
import { InputSection } from "components/InputSection"
import { AnswerSection } from "components/AnswerSection"

const Home: NextPage = () => {
  const openai = new OpenAI({
    apiKey: process.env.NEXT_PUBLIC_OPENAI_API_KEY,
    dangerouslyAllowBrowser: true,
  })

  const [storedValues, setStoredValues] = useState<StoredValue[]>([])

  const generateResponse = async (queue: any, setQueue: any) => {
    const chatCompletion = await openai.chat.completions.create({
      messages: [
        {
          role: "user",
          content: `You are a novelist. Based on the Japanese short sentences you will now input, please output a part of a novel. The part of the novel must satisfy the conditions of being "more than 50 characters but less than 200 characters in length" and "in Japanese." The Japanese short sentence is ${queue}.`,
        },
      ],
      model: "gpt-4",
    })

    if (chatCompletion.choices) {
      setStoredValues([
        {
          question: queue,
          answer: chatCompletion.choices[0].message.content?.toString(),
        },
        ...storedValues,
      ])
      setQueue("")

      // JSONファイルに保存
      const res = await fetch("/api", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          id: 1,
          content: chatCompletion.choices[0].message.content?.toString(),
          updatedAt: new Date().toISOString(),
        }),
      })

      const data = await res.json();
      // if (res.ok) {
      //   setMessage('Story updated successfully!');
      // } else {
      //   setMessage(data.message || 'An error occurred');
      // }

      // for dev use
      console.log(chatCompletion)
      console.log(data)
    }
  }

  return (
    <div>
      <Header />
      <StoryReader />
      <InputSection generateResponse={generateResponse} />
      <AnswerSection storedValues={storedValues} />
    </div>
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{" "}
    //       <code className={styles.code}>pages/index.tsx</code>
    //     </p>

    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/canary/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{" "}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
  )
}

export default Home
